name: test_visioad_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  dio: ^5.7.0
  retrofit: ^4.1.0
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  dart_either: ^2.0.0
  get_it: ^7.7.0
  freezed_annotation: ^2.4.1
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.0
  intl: ^0.18.0
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.4
  pull_to_refresh: ^2.0.0
  device_preview: ^1.1.0
  connectivity_plus: ^6.0.5






  cupertino_icons: ^1.0.6
  sqflite: ^2.3.3+1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  retrofit_generator: '>=5.0.0 <6.0.0'
  freezed: ^2.5.2
  dropdown_search: ^5.0.6
  cached_network_image: ^3.3.1


  flutter_localizations:
    sdk: flutter

flutter_intl:
    main_locale: en
    enabled: true
    output_dir: lib/src/core/translations
    arb_dir: lib/src/core/translations


intl:
    shared_preferences: ^2.2.0
    sqflite: ^2.3.0
    path_provider: ^2.0.15


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/no_image.png



  # To add assets to your application, add an assets section, like this:


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
